require('settings')
require('mappings')
require('colorscheme-config')
require('packer-config')
require('nvim-tree-config')
require('lsp-config.language-servers')
require('lsp-config.nvim-cmp')
require('treesitter-config')
require('treesitter-refactor-config')
require('telescope-config')
require('nvim-autopairs').setup{}
require('lualine').setup()
-- require('bufferline-config')
require("commentary").setup({})
require('nvim-terminal-config')
