return {
    "adibhanna/laravel.nvim",
    dependencies = {
        "MunifTanjim/nui.nvim",
        "nvim-lua/plenary.nvim",
        "nvim-telescope/telescope.nvim",
    },
    cmd = { "Artisan", "Composer", "LaravelRoute", "LaravelMake", "LaravelFinder", "LaravelViews", "LaravelConfig", "LaravelMigrations", "LaravelModels", "LaravelControllers" },
    keys = {
        { "<leader>la",  ":Artisan<cr>",            desc = "Laravel Artisan" },
        { "<leader>lc",  ":Composer<cr>",           desc = "Composer" },
        { "<leader>lr",  ":LaravelRoute<cr>",       desc = "Laravel Routes" },
        { "<leader>lm",  ":LaravelMake<cr>",        desc = "Laravel Make" },
        { "<leader>lf",  ":LaravelFinder<cr>",      desc = "Laravel Finder" },
        { "<leader>lv",  ":LaravelViews<cr>",       desc = "Laravel Views" },
        { "<leader>lcf", ":LaravelConfig<cr>",      desc = "Laravel Config" },
        { "<leader>lmc", ":LaravelMigrations<cr>",  desc = "Laravel Migrations" },
        { "<leader>lmd", ":LaravelModels<cr>",      desc = "Laravel Models" },
        { "<leader>lct", ":LaravelControllers<cr>", desc = "Laravel Controllers" },
    },
    ft = { "php", "blade" },
    config = function()
        require("laravel").setup({
            -- Laravel executable path
            lsp_server = "intelephense",
            -- Options passed to lsp
            lsp_options = {
                settings = {
                    intelephense = {
                        files = {
                            maxSize = 5000000,
                            associations = { "*.php", "*.blade.php" },
                            exclude = {
                                "**/.git/**",
                                "**/.svn/**",
                                "**/.hg/**",
                                "**/CVS/**",
                                "**/.DS_Store/**",
                                "**/node_modules/**",
                                "**/bower_components/**",
                                "**/vendor/**/{Tests,tests}/**",
                                "**/.history/**",
                                "**/vendor/**/vendor/**",
                            },
                        },
                        stubs = {
                            "apache",
                            "bcmath",
                            "bz2",
                            "calendar",
                            "com_dotnet",
                            "Core",
                            "ctype",
                            "curl",
                            "date",
                            "dba",
                            "dom",
                            "enchant",
                            "exif",
                            "fileinfo",
                            "filter",
                            "fpm",
                            "ftp",
                            "gd",
                            "hash",
                            "iconv",
                            "imap",
                            "intl",
                            "json",
                            "ldap",
                            "libxml",
                            "mbstring",
                            "mcrypt",
                            "meta",
                            "mysqli",
                            "oci8",
                            "odbc",
                            "openssl",
                            "pcntl",
                            "pcre",
                            "PDO",
                            "pdo_ibm",
                            "pdo_mysql",
                            "pdo_pgsql",
                            "pdo_sqlite",
                            "pgsql",
                            "Phar",
                            "posix",
                            "pspell",
                            "readline",
                            "recode",
                            "Reflection",
                            "regex",
                            "session",
                            "SimpleXML",
                            "snmp",
                            "soap",
                            "sockets",
                            "sodium",
                            "SPL",
                            "sqlite3",
                            "standard",
                            "superglobals",
                            "sysvsem",
                            "sysvshm",
                            "tidy",
                            "tokenizer",
                            "xml",
                            "xmlreader",
                            "xmlrpc",
                            "xmlwriter",
                            "xsl",
                            "Zend OPcache",
                            "zip",
                            "zlib",
                            "wordpress",
                            "woocommerce",
                            "acf-pro",
                            "wordpress-globals",
                            "wp-cli",
                            "genesis",
                            "polylang",
                            "laravel",
                        },
                        environment = {
                            includePaths = { "vendor/laravel/framework/src/" },
                        },
                        completion = {
                            insertUseDeclaration = true,
                            fullyQualifyGlobalConstantsAndFunctions = false,
                            triggerParameterHints = true,
                            maxItems = 100,
                        },
                        format = {
                            enable = true,
                            braces = "psr12",
                        },
                        diagnostics = {
                            enable = true,
                            run = "onType",
                            embeddedLanguages = true,
                        },
                        rename = {
                            exclude = {
                                "**/vendor/**",
                                "**/node_modules/**",
                            },
                        },
                        references = {
                            exclude = {
                                "**/vendor/**",
                                "**/node_modules/**",
                            },
                        },
                    },
                },
            },
            -- Register the Blade parser with the Laravel plugin
            blade = {
                enable = true,
            },
            -- Define Laravel-specific features
            features = {
                route_info = {
                    enable = true,
                    position = "top",
                    middlewares = true,
                },
                model_info = {
                    enable = true,
                    position = "right",
                    include_columns = true,
                },
            },
        })
    end,
}
